### ISSUE TITLE
:ns(-exclude)-regex can't be used in tests.edn due to regex reading issue

### ISSUE THREAD

**Issue by tanzoniteblack** [lambdaisland/kaocha-cloverage#1]
`:ns-exclude-regex` and `:ns-regex` work from command line args, because they're mapped to regex patterns, but if added directly in the `tests.edn`, this conversion never takes place, but there's no edn reader for regexes. What happens is you end up getting the following exception when running: 

```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.regex.Pattern (java.lang.String and java.util.regex.Pattern are in module java.base of loader 'bootstrap')
```

**Comment by AndreaCrotti** [comment]
I guess this can be closed at least after https://github.com/lambdaisland/kaocha-cloverage/pull/11is merged

**Comment by AndreaCrotti** [comment]
Yes @tanzoniteblack you should try with the latest version and it should be fixed.

**Comment by arichiardi** [comment]
Given this is open still, wanted to say that it does not work here. I get a different error though with:

`:ns-exclude-regex ["com\.foo\.core2\..*\.interfaces.*"]`

It seems like `re-pattern` regexp(s) should be pre-processed by `java.util.regex.Pattern.quote` before, see here:

https://stackoverflow.com/a/3675086/1888507

**Comment by plexus** [comment]
If we preprocess with `Pattern/quote` then you would only be able to match on literal strings, any special characters like `.` or `*` would get quoted.
In your example you need to use double backslashes to quote.

```clj
user> (re-pattern "com\\.foo\\.core2\\..*\\.interfaces.*")
#"com\.foo\.core2\..*\.interfaces.*"
```
This will cause the backslashes to be present in the string, so that they are picked up by re-pattern. Your example is not a valid string, since `\.` is not a valid escape sequence inside strings.

```clj
Clojure 1.10.0
user=> "\."
Syntax error reading source at (REPL:1:4).
Unsupported escape character: \.
```

**Comment by alysbrooks** [comment]
@arichiardi Do you have any other questions/issues with regular expressions? (@plexus is there another reason to keep this open?)

**Comment by plexus** [comment]
No, I don't think so.
