### ISSUE TITLE
Run tests in PRs?

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha-cloverage#12]
I think it's just a bit of extra configuration in circleci to set it up to run the test suite for PRs, would be quite useful to make sure to the casual contributor to make sure that nothing was broken.

**Comment by plexus** [comment]
I'm sorry @AndreaCrotti can you be more clear? I feel like I'm dropping into the middle of a conversation where I missed the first half. What's the problem and what solution are you proposing?

**Comment by AndreaCrotti** [comment]
Ah well just the fact that I don't see a link to Circleci in my PR https://github.com/lambdaisland/kaocha-cloverage/pull/11, so it's a bit harder to see if broke something since I can't run the tests locally in the same way as circleci would..

**Comment by AndreaCrotti** [comment]
It should just be this setting https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by plexus** [comment]
Ah I get it now :) I didn't realize this was a "meta" issue about the project setup. I've enabled the setting.

**Comment by AndreaCrotti** [comment]
Ok great thanks, they isn't meta-issue category unfortunately 😄
