### ISSUE TITLE
Feature Request: support for https://cobertura.github.io/cobertura/ 

### ISSUE THREAD

**Issue by jasonjckn** [lambdaisland/kaocha-cloverage#20]
I was looking to take advantage of GitLab's coverage visualizer, 
https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html

but .... 

> For the coverage analysis to work, you have to provide a properly formatted [Cobertura XML](https://cobertura.github.io/cobertura/) report to [artifacts:reports:coverage_report](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscoverage_report). **This format was originally developed for Java**, but most coverage analysis frameworks for other languages have plugins to add support for it, like:

How hard would it be to add this?

**Comment by plexus** [comment]
The cloverage project would be a better place to ask this.

**Comment by alysbrooks** [comment]
I think we'd welcome a PR to bring upstream support for this into `kaocha-cloverage`, but this will not be a priority most likely.
